DROP TABLE CONTACTS;
COMMIT;
CREATE TABLE CONTACTS
(
    C_ID    INTEGER GENERATED ALWAYS AS IDENTITY
                 (START WITH 1, INCREMENT BY 1, NO CACHE, NO CYCLE),
    LANG  CHARACTER(2) NOT NULL,
    SURNAME  VARCHAR(30) NOT NULL,
    FIRST_NAME  VARCHAR(30) NOT NULL,
    MIDDLE_NAME  VARCHAR(30),
    ADDL_NAME  VARCHAR(30),
    EMAIL_ADDR  VARCHAR(40) NOT NULL,
    LAST_CONTACT  DATE,
    LAST_RESPONSE  DATE,
    DO_NOT_CONTACT  CHARACTER(1),

    CONSTRAINT PK_ID PRIMARY KEY (C_ID),
    CONSTRAINT CHK_LANG CHECK (LANG IN ('EN', 'ES')),
    CONSTRAINT CHK_DO_NOT_CONTACT CHECK (
      DO_NOT_CONTACT IN ('X','P')
      OR DO_NOT_CONTACT IS NULL
    )
)
IN DBMATE1.TSMATEGD;                                                    e
COMMIT;

CREATE UNIQUE INDEX CONTACTS_PK ON CONTACTS(C_ID);
COMMIT;

INSERT INTO CONTACTS (
  LANG, SURNAME, FIRST_NAME, MIDDLE_NAME, ADDL_NAME,
  EMAIL_ADDR, LAST_CONTACT, LAST_RESPONSE, DO_NOT_CONTACT)
VALUES (
  'EN', 'SALAMADISY', 'ALI', 'MOHAMMED', NULL,
  'SALA@NOWHERE.COM', DATE '2024-03-15', NULL, NULL);

INSERT INTO CONTACTS (
  LANG, SURNAME, FIRST_NAME, MIDDLE_NAME, ADDL_NAME,
  EMAIL_ADDR, LAST_CONTACT, LAST_RESPONSE, DO_NOT_CONTACT)
VALUES (
  'EN', 'THACKERAY', 'JACKSON', 'PETER', NULL,
  'JACK.THACK@NOWHERE.COM', DATE '2024-03-15', DATE '2024-03-22','P');

INSERT INTO CONTACTS (
  LANG, SURNAME, FIRST_NAME, MIDDLE_NAME, ADDL_NAME,
  EMAIL_ADDR, LAST_CONTACT, LAST_RESPONSE, DO_NOT_CONTACT)
VALUES (
  'EN', 'TAYLOR', 'MADISON', 'CYNTHIA', NULL,
  'SALAMANDER@NOWHERE.COM', DATE '2024-03-15', NULL, NULL);

INSERT INTO CONTACTS (
  LANG, SURNAME, FIRST_NAME, MIDDLE_NAME, ADDL_NAME,
  EMAIL_ADDR, LAST_CONTACT, LAST_RESPONSE, DO_NOT_CONTACT)
VALUES (
  'EN', 'EKLUND', 'BJORN', 'FREDERIK', NULL,
  'EKLUND.B@NOWHERE.COM', NULL, NULL, NULL);
